### ISSUE TITLE
plugin not replacing placeholder 

### ISSUE THREAD

**Issue by gehal6** [argoproj-labs/argocd-vault-plugin#479]
**Describe the bug**
Hi All,
kindly I have helm,argocd and hashicorp vault.
I am implementing "Argo CD Vault Plugin" so it can read the placeholders and change it with the value from the hashicorp vault.
I tried the plugin with command line on mac device to test the plugin in argo and works perfectly for the same helmchart and connection is opened to the vault from local.
command "helm template keycloak-config ./chart-name -f chart-name/dev-values.yaml | argocd-vault-plugin generate -c /tmp/vaultconfig.yaml"
but on argocd the plugin is installed and I can deploy using it although the placeholders doesn't change for example <password> goes in EKS secrets <password> wthout changing with the value in the vault
I appreciate your support very much, it has been a week looking into this one

**To Reproduce**
install plugin with init containers and ConfigMap

**Expected behavior**
if the yaml has 
stringData: 
  password: <POSTGRES_PASSWORD> 

in the k8s secrets the password value goes like <POSTGRES_PASSWORD>  without getting changed

**Screenshots/Verbose output**

If you've tried running `argocd-vault-plugin generate` with `--verbose-sensitive-output` to help debug, please include that output here after redacting any secrets.

**Additional context**

**Comment by werne2j** [comment]
Can you please provide your application manifest, the full yaml with the placeholders and how you’re setting up AVP?

**Comment by gehal6** [comment]
Hi Jacob,

Kindly I attached the following
1. the complete manifest "argocd.yaml" of argocd objects.
2. the yaml with the placeholders "secrets.yaml"

I am setting the AVP using the options "InitContainer and configuration via
argocd-cm ConfigMap" in the documentation
https://argocd-vault-plugin.readthedocs.io/en/stable/installation/

I have read in some blog that this installation not supported since version
2.4.0 although argo official documentation not stating that.
please confirm so I can act upon your reply.

Thanks,
George Halim

**Comment by werne2j** [comment]
@gehal6 Looks like the yamls never got uploaded to github. Can you add them in the comments?

**Comment by kaiquerass** [comment]
Same issue here, the secret value is created exactly as the placeholder. `<path:secrets/data/helm#CUSTOM_ENV>`
I ran ssh to the repo-server pod and the command `argocd-vault-plugin generate` worked perfect, the placeholder is changed to the secret value.
But when I sync the application, it does not work.

**Comment by kaiquerass** [comment]
but if it was env vars problems, the container would not be able to run the command and make connection to vault, right? 
sorry, but I didn't get the point.
I mean, the container is actually working the command when I run manually, but the argo executing the plugin is not.

**Comment by kaiquerass** [comment]
I was able to fix it.

I removed the plugin configuration from the application manifest and it worked!

**Comment by GeorgeWasla** [comment]
@kaiquerass can I know which approach did you follow in the vault plugin installation?

**Comment by kaiquerass** [comment]
for people having this problem: 
argo will automatically discover which plugin to use based on the discover section of the plugin, so write a discover command that will fit your application.
then remove the plugin config in application manifest: 
```
source:
  repoURL: ''
  path: charts
  targetRevision: HEAD
  plugin: {}
```

**Comment by kaiquerass** [comment]
I'm using as sidecar @GeorgeWasla

**Comment by epetrovski-endava** [comment]
@kaiquerass could you please elaborate a bit more on the discover command that you wrote? my AVP works with regular manifests in .yaml format, but I'm passing a custom values.yaml file for my chart and for some reason the placeholder isn't being replaced in the values.yaml file, but regular manifests in .yaml are replacing the placeholder

**Comment by GeorgeWasla** [comment]
@epetrovski-endava I fixed the issue, the problem happens when installing argocd using manifest in the documentation to fix that you need to use the helm chart instead

**Comment by gehal6** [comment]
@epetrovski-endava I fixed the issue, the problem happens when installing argocd using manifest in the documentation to fix that you need to use the helm chart instead

**Comment by epetrovski-endava** [comment]
@gehal6 Could you please elaborate a bit further? I'm not sure I understand what exactly is needed to fix this. I added the three plugins (avp, avp-kustomize, avp-helm) in my ArgoCD values.yaml, under config.cmp, chart version 5.26.0, and the plugin still does not replace the placeholder when I am adding it in my values.yaml of the application that I use.

Do I need to modify my application.yaml? Thank you

**Comment by yossigilad** [comment]
@epetrovski-endava I'm having same issue in my environment, did you succeded to solve yours issue?

**Comment by aleksandarilic96** [comment]
> for people having this problem: argo will automatically discover which plugin to use based on the discover section of the plugin, so write a discover command that will fit your application. then remove the plugin config in application manifest:
> 
> ```
> source:
>   repoURL: ''
>   path: charts
>   targetRevision: HEAD
>   plugin: {}
> ```

@kaiquerass Could you give more detail about this I'm using https://github.com/luafanti/spring-boot-debug-app/tree/main/infra/helm for testing but values set in https://github.com/luafanti/spring-boot-debug-app/blob/main/infra/argocd/argocd-application-with-vault-secrets.yaml this app manifest are not being replaced

**Comment by Zoli8501** [comment]
Same issue for me as well: 
replaceString: missing Vault value for placeholder password in string password: <password>
I tried to let argo automatically discover the plugin: plugin: {},
but same error.

**Comment by obriat** [comment]
H,
I don't know if it's related but I would like to inject secret as env vars dynamically during deployment. 

I declared the mapping in my app ARGOCD MANIFEST: 
``` 
  plugin:
    name: my-argocd-vault-plugin-helm
    env:
      - name: HELM_VALUES
        value: |
          namespace: my-namespace
          varenv: 
            ENV1: <path:secret/data/path/my_env#ENV1>
            ENV2: <path:secret/data/path/my_env#ENV2>
            ...
``` 

But when I try to use a `range` on ` .Values.varenv` in deployment:
``` ...
          env:
          {{- range $key, $value := .Values.varenv }}
            - name: {{ $key }}
              value: {{ $value}} 
          {{- end }}  
```

I got the following error  "Error: Replace: could not replace all placeholders in Template:  replaceString: missing Vault value for placeholder path:secret/data/path/secret1#ENV1 in string ..."


I finally manage  to trick it by using the following code in a configMapRef : 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: my-app-env-configmap
data:
  {{- range $key, $value := .Values.varenv }}
    {{ $key }}: {{ $key | printf "{{ .Values.varenv.%s }}" | quote }}
  {{- end }}
```

But I guess there a better way.

The ultimate goal whould be to inject all the keys in a var:
``` 
  plugin:
    name: my-argocd-vault-plugin-helm
    env:
      - name: HELM_VALUES
        value: |
          namespace: my-namespace
          varenv: ENV1: <path:secret/data/path/my_env>
...
```
then
``` ...
          env:  {{ .Values.varenv }}
```
